server:
  port: 6868
eureka:
  client:
    register-with-eureka: false #是否将自己注册到Eureka中。本身就是Eureka，所以不用注册
    fetch-registry: false #是否从Eureka获取注册信息
    service-url: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:${server.port}/eureka/